// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: activity_logs.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createActivityLog = `-- name: CreateActivityLog :one
INSERT INTO activity_logs (user_type, user_id, session_id, action, details, ip_address)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, user_type, user_id, session_id, action, details, ip_address, created_at
`

type CreateActivityLogParams struct {
	UserType  string      `json:"user_type"`
	UserID    int32       `json:"user_id"`
	SessionID pgtype.Text `json:"session_id"`
	Action    string      `json:"action"`
	Details   []byte      `json:"details"`
	IpAddress pgtype.Text `json:"ip_address"`
}

func (q *Queries) CreateActivityLog(ctx context.Context, arg CreateActivityLogParams) (ActivityLog, error) {
	row := q.db.QueryRow(ctx, createActivityLog,
		arg.UserType,
		arg.UserID,
		arg.SessionID,
		arg.Action,
		arg.Details,
		arg.IpAddress,
	)
	var i ActivityLog
	err := row.Scan(
		&i.ID,
		&i.UserType,
		&i.UserID,
		&i.SessionID,
		&i.Action,
		&i.Details,
		&i.IpAddress,
		&i.CreatedAt,
	)
	return i, err
}

const getActivityLogsForUser = `-- name: GetActivityLogsForUser :many
SELECT id, user_type, user_id, session_id, action, details, ip_address, created_at
FROM activity_logs
WHERE user_type = $1 AND user_id = $2
ORDER BY created_at DESC
LIMIT $3
`

type GetActivityLogsForUserParams struct {
	UserType string `json:"user_type"`
	UserID   int32  `json:"user_id"`
	Limit    int32  `json:"limit"`
}

func (q *Queries) GetActivityLogsForUser(ctx context.Context, arg GetActivityLogsForUserParams) ([]ActivityLog, error) {
	rows, err := q.db.Query(ctx, getActivityLogsForUser, arg.UserType, arg.UserID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ActivityLog
	for rows.Next() {
		var i ActivityLog
		if err := rows.Scan(
			&i.ID,
			&i.UserType,
			&i.UserID,
			&i.SessionID,
			&i.Action,
			&i.Details,
			&i.IpAddress,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getActivityLogsForUserSessions = `-- name: GetActivityLogsForUserSessions :many
SELECT al.id, al.user_type, al.user_id, al.session_id, al.action, al.details, al.ip_address, al.created_at
FROM activity_logs al
WHERE al.user_type = $1 AND al.user_id = $2
  AND al.session_id IN (
      SELECT DISTINCT session_id
      FROM activity_logs
      WHERE user_type = $1 AND user_id = $2 AND session_id IS NOT NULL AND session_id != ''
      ORDER BY session_id DESC
      LIMIT $3
  )
ORDER BY al.created_at DESC
`

type GetActivityLogsForUserSessionsParams struct {
	UserType string `json:"user_type"`
	UserID   int32  `json:"user_id"`
	Limit    int32  `json:"limit"`
}

// Get activity logs for the last N distinct sessions of a user
func (q *Queries) GetActivityLogsForUserSessions(ctx context.Context, arg GetActivityLogsForUserSessionsParams) ([]ActivityLog, error) {
	rows, err := q.db.Query(ctx, getActivityLogsForUserSessions, arg.UserType, arg.UserID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ActivityLog
	for rows.Next() {
		var i ActivityLog
		if err := rows.Scan(
			&i.ID,
			&i.UserType,
			&i.UserID,
			&i.SessionID,
			&i.Action,
			&i.Details,
			&i.IpAddress,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getDistinctSessionsForUser = `-- name: GetDistinctSessionsForUser :many
SELECT
    session_id,
    MIN(created_at) AS session_start,
    MAX(created_at) AS session_end,
    COUNT(*) AS action_count
FROM activity_logs
WHERE user_type = $1 AND user_id = $2 AND session_id IS NOT NULL AND session_id != ''
GROUP BY session_id
ORDER BY MIN(created_at) DESC
LIMIT $3
`

type GetDistinctSessionsForUserParams struct {
	UserType string `json:"user_type"`
	UserID   int32  `json:"user_id"`
	Limit    int32  `json:"limit"`
}

type GetDistinctSessionsForUserRow struct {
	SessionID    pgtype.Text `json:"session_id"`
	SessionStart interface{} `json:"session_start"`
	SessionEnd   interface{} `json:"session_end"`
	ActionCount  int64       `json:"action_count"`
}

// Get distinct sessions for a user with first and last activity timestamps
func (q *Queries) GetDistinctSessionsForUser(ctx context.Context, arg GetDistinctSessionsForUserParams) ([]GetDistinctSessionsForUserRow, error) {
	rows, err := q.db.Query(ctx, getDistinctSessionsForUser, arg.UserType, arg.UserID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetDistinctSessionsForUserRow
	for rows.Next() {
		var i GetDistinctSessionsForUserRow
		if err := rows.Scan(
			&i.SessionID,
			&i.SessionStart,
			&i.SessionEnd,
			&i.ActionCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getRecentActivityLogs = `-- name: GetRecentActivityLogs :many
SELECT al.id, al.user_type, al.user_id, al.session_id, al.action, al.details, al.ip_address, al.created_at
FROM activity_logs al
ORDER BY al.created_at DESC
LIMIT $1
`

// Get recent activity across all users
func (q *Queries) GetRecentActivityLogs(ctx context.Context, limit int32) ([]ActivityLog, error) {
	rows, err := q.db.Query(ctx, getRecentActivityLogs, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ActivityLog
	for rows.Next() {
		var i ActivityLog
		if err := rows.Scan(
			&i.ID,
			&i.UserType,
			&i.UserID,
			&i.SessionID,
			&i.Action,
			&i.Details,
			&i.IpAddress,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
