// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.0
// source: admins.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countPlatformStats = `-- name: CountPlatformStats :one
SELECT
    (SELECT COUNT(*) FROM veterans) AS total_veterans,
    (SELECT COUNT(*) FROM employers) AS total_employers,
    (SELECT COUNT(*) FROM job_listings WHERE is_active = true) AS active_listings,
    (SELECT COUNT(*) FROM veteran_applications WHERE status != 'matched') AS total_applications,
    (SELECT COUNT(*) FROM veteran_applications WHERE status = 'placed') AS total_placements
`

type CountPlatformStatsRow struct {
	TotalVeterans     int64 `json:"total_veterans"`
	TotalEmployers    int64 `json:"total_employers"`
	ActiveListings    int64 `json:"active_listings"`
	TotalApplications int64 `json:"total_applications"`
	TotalPlacements   int64 `json:"total_placements"`
}

func (q *Queries) CountPlatformStats(ctx context.Context) (CountPlatformStatsRow, error) {
	row := q.db.QueryRow(ctx, countPlatformStats)
	var i CountPlatformStatsRow
	err := row.Scan(
		&i.TotalVeterans,
		&i.TotalEmployers,
		&i.ActiveListings,
		&i.TotalApplications,
		&i.TotalPlacements,
	)
	return i, err
}

const createAdmin = `-- name: CreateAdmin :one
INSERT INTO admins (email, password_hash, name)
VALUES ($1, $2, $3)
ON CONFLICT (email) DO NOTHING
RETURNING id, email, password_hash, name, created_at, updated_at
`

type CreateAdminParams struct {
	Email        string `json:"email"`
	PasswordHash string `json:"password_hash"`
	Name         string `json:"name"`
}

func (q *Queries) CreateAdmin(ctx context.Context, arg CreateAdminParams) (Admin, error) {
	row := q.db.QueryRow(ctx, createAdmin, arg.Email, arg.PasswordHash, arg.Name)
	var i Admin
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.PasswordHash,
		&i.Name,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getAdminByEmail = `-- name: GetAdminByEmail :one
SELECT id, email, password_hash, name, created_at, updated_at
FROM admins
WHERE email = $1
`

func (q *Queries) GetAdminByEmail(ctx context.Context, email string) (Admin, error) {
	row := q.db.QueryRow(ctx, getAdminByEmail, email)
	var i Admin
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.PasswordHash,
		&i.Name,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getAdminByID = `-- name: GetAdminByID :one
SELECT id, email, password_hash, name, created_at, updated_at
FROM admins
WHERE id = $1
`

func (q *Queries) GetAdminByID(ctx context.Context, id int32) (Admin, error) {
	row := q.db.QueryRow(ctx, getAdminByID, id)
	var i Admin
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.PasswordHash,
		&i.Name,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listAllApplications = `-- name: ListAllApplications :many
SELECT
    va.id, va.status, va.match_score, va.created_at, va.updated_at,
    v.id AS veteran_id, v.name AS veteran_name, v.email AS veteran_email, v.mos_code,
    jl.id AS job_listing_id, jl.title AS job_title,
    e.company_name
FROM veteran_applications va
JOIN veterans v ON v.id = va.veteran_id
JOIN job_listings jl ON jl.id = va.job_listing_id
JOIN employers e ON e.id = jl.employer_id
WHERE va.status != 'matched'
ORDER BY va.updated_at DESC
LIMIT 100
`

type ListAllApplicationsRow struct {
	ID           int32              `json:"id"`
	Status       string             `json:"status"`
	MatchScore   int32              `json:"match_score"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	UpdatedAt    pgtype.Timestamptz `json:"updated_at"`
	VeteranID    int32              `json:"veteran_id"`
	VeteranName  string             `json:"veteran_name"`
	VeteranEmail string             `json:"veteran_email"`
	MosCode      pgtype.Text        `json:"mos_code"`
	JobListingID int32              `json:"job_listing_id"`
	JobTitle     string             `json:"job_title"`
	CompanyName  string             `json:"company_name"`
}

func (q *Queries) ListAllApplications(ctx context.Context) ([]ListAllApplicationsRow, error) {
	rows, err := q.db.Query(ctx, listAllApplications)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListAllApplicationsRow
	for rows.Next() {
		var i ListAllApplicationsRow
		if err := rows.Scan(
			&i.ID,
			&i.Status,
			&i.MatchScore,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.VeteranID,
			&i.VeteranName,
			&i.VeteranEmail,
			&i.MosCode,
			&i.JobListingID,
			&i.JobTitle,
			&i.CompanyName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAllEmployers = `-- name: ListAllEmployers :many
SELECT id, email, company_name, contact_name, sector, location, description, is_active, created_at, updated_at
FROM employers
ORDER BY created_at DESC
`

type ListAllEmployersRow struct {
	ID          int32              `json:"id"`
	Email       string             `json:"email"`
	CompanyName string             `json:"company_name"`
	ContactName string             `json:"contact_name"`
	Sector      string             `json:"sector"`
	Location    string             `json:"location"`
	Description string             `json:"description"`
	IsActive    bool               `json:"is_active"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) ListAllEmployers(ctx context.Context) ([]ListAllEmployersRow, error) {
	rows, err := q.db.Query(ctx, listAllEmployers)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListAllEmployersRow
	for rows.Next() {
		var i ListAllEmployersRow
		if err := rows.Scan(
			&i.ID,
			&i.Email,
			&i.CompanyName,
			&i.ContactName,
			&i.Sector,
			&i.Location,
			&i.Description,
			&i.IsActive,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAllJobListings = `-- name: ListAllJobListings :many
SELECT
    jl.id, jl.title, jl.description, jl.location,
    jl.salary_min, jl.salary_max, jl.employment_type, jl.wotc_eligible,
    jl.is_active, jl.posted_at,
    e.company_name,
    cr.title AS role_title, cr.sector
FROM job_listings jl
JOIN employers e ON e.id = jl.employer_id
JOIN civilian_roles cr ON cr.id = jl.civilian_role_id
ORDER BY jl.posted_at DESC
`

type ListAllJobListingsRow struct {
	ID             int32              `json:"id"`
	Title          string             `json:"title"`
	Description    string             `json:"description"`
	Location       string             `json:"location"`
	SalaryMin      int32              `json:"salary_min"`
	SalaryMax      int32              `json:"salary_max"`
	EmploymentType string             `json:"employment_type"`
	WotcEligible   bool               `json:"wotc_eligible"`
	IsActive       bool               `json:"is_active"`
	PostedAt       pgtype.Timestamptz `json:"posted_at"`
	CompanyName    string             `json:"company_name"`
	RoleTitle      string             `json:"role_title"`
	Sector         string             `json:"sector"`
}

func (q *Queries) ListAllJobListings(ctx context.Context) ([]ListAllJobListingsRow, error) {
	rows, err := q.db.Query(ctx, listAllJobListings)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListAllJobListingsRow
	for rows.Next() {
		var i ListAllJobListingsRow
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Description,
			&i.Location,
			&i.SalaryMin,
			&i.SalaryMax,
			&i.EmploymentType,
			&i.WotcEligible,
			&i.IsActive,
			&i.PostedAt,
			&i.CompanyName,
			&i.RoleTitle,
			&i.Sector,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAllVeterans = `-- name: ListAllVeterans :many
SELECT id, email, name, mos_code, rank, years_of_service, separation_date, location, preferred_sectors, journey_step, created_at, updated_at
FROM veterans
ORDER BY created_at DESC
`

type ListAllVeteransRow struct {
	ID               int32              `json:"id"`
	Email            string             `json:"email"`
	Name             string             `json:"name"`
	MosCode          pgtype.Text        `json:"mos_code"`
	Rank             string             `json:"rank"`
	YearsOfService   int32              `json:"years_of_service"`
	SeparationDate   pgtype.Date        `json:"separation_date"`
	Location         string             `json:"location"`
	PreferredSectors []string           `json:"preferred_sectors"`
	JourneyStep      string             `json:"journey_step"`
	CreatedAt        pgtype.Timestamptz `json:"created_at"`
	UpdatedAt        pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) ListAllVeterans(ctx context.Context) ([]ListAllVeteransRow, error) {
	rows, err := q.db.Query(ctx, listAllVeterans)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListAllVeteransRow
	for rows.Next() {
		var i ListAllVeteransRow
		if err := rows.Scan(
			&i.ID,
			&i.Email,
			&i.Name,
			&i.MosCode,
			&i.Rank,
			&i.YearsOfService,
			&i.SeparationDate,
			&i.Location,
			&i.PreferredSectors,
			&i.JourneyStep,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateAdminPassword = `-- name: UpdateAdminPassword :exec
UPDATE admins SET password_hash = $2, updated_at = NOW()
WHERE id = $1
`

type UpdateAdminPasswordParams struct {
	ID           int32  `json:"id"`
	PasswordHash string `json:"password_hash"`
}

func (q *Queries) UpdateAdminPassword(ctx context.Context, arg UpdateAdminPasswordParams) error {
	_, err := q.db.Exec(ctx, updateAdminPassword, arg.ID, arg.PasswordHash)
	return err
}
