// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: applications.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countVeteranApplicationsByStatus = `-- name: CountVeteranApplicationsByStatus :many
SELECT status, COUNT(*) AS count
FROM veteran_applications
WHERE veteran_id = $1
GROUP BY status
`

type CountVeteranApplicationsByStatusRow struct {
	Status string `json:"status"`
	Count  int64  `json:"count"`
}

func (q *Queries) CountVeteranApplicationsByStatus(ctx context.Context, veteranID int32) ([]CountVeteranApplicationsByStatusRow, error) {
	rows, err := q.db.Query(ctx, countVeteranApplicationsByStatus, veteranID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []CountVeteranApplicationsByStatusRow
	for rows.Next() {
		var i CountVeteranApplicationsByStatusRow
		if err := rows.Scan(&i.Status, &i.Count); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const createOrGetApplication = `-- name: CreateOrGetApplication :one
INSERT INTO veteran_applications (veteran_id, job_listing_id, status, match_score)
VALUES ($1, $2, $3, $4)
ON CONFLICT (veteran_id, job_listing_id) DO UPDATE SET
    status = CASE
        WHEN veteran_applications.status = 'matched' THEN EXCLUDED.status
        ELSE veteran_applications.status
    END,
    updated_at = NOW()
RETURNING id, veteran_id, job_listing_id, status, match_score, notes, created_at, updated_at
`

type CreateOrGetApplicationParams struct {
	VeteranID    int32  `json:"veteran_id"`
	JobListingID int32  `json:"job_listing_id"`
	Status       string `json:"status"`
	MatchScore   int32  `json:"match_score"`
}

type CreateOrGetApplicationRow struct {
	ID           int32              `json:"id"`
	VeteranID    int32              `json:"veteran_id"`
	JobListingID int32              `json:"job_listing_id"`
	Status       string             `json:"status"`
	MatchScore   int32              `json:"match_score"`
	Notes        string             `json:"notes"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	UpdatedAt    pgtype.Timestamptz `json:"updated_at"`
}

// Creates an application if it doesn't exist, or returns the existing one
func (q *Queries) CreateOrGetApplication(ctx context.Context, arg CreateOrGetApplicationParams) (CreateOrGetApplicationRow, error) {
	row := q.db.QueryRow(ctx, createOrGetApplication,
		arg.VeteranID,
		arg.JobListingID,
		arg.Status,
		arg.MatchScore,
	)
	var i CreateOrGetApplicationRow
	err := row.Scan(
		&i.ID,
		&i.VeteranID,
		&i.JobListingID,
		&i.Status,
		&i.MatchScore,
		&i.Notes,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const ensureMatchedApplications = `-- name: EnsureMatchedApplications :exec
INSERT INTO veteran_applications (veteran_id, job_listing_id, status, match_score)
SELECT $1, jl.id, 'matched', mcm.match_score
FROM mos_civilian_mappings mcm
JOIN job_listings jl ON jl.civilian_role_id = mcm.civilian_role_id AND jl.is_active = true
WHERE mcm.mos_code = $2
ON CONFLICT (veteran_id, job_listing_id) DO NOTHING
`

type EnsureMatchedApplicationsParams struct {
	VeteranID int32  `json:"veteran_id"`
	MosCode   string `json:"mos_code"`
}

// Auto-create matched applications for a veteran based on their MOS
func (q *Queries) EnsureMatchedApplications(ctx context.Context, arg EnsureMatchedApplicationsParams) error {
	_, err := q.db.Exec(ctx, ensureMatchedApplications, arg.VeteranID, arg.MosCode)
	return err
}

const getVeteranApplication = `-- name: GetVeteranApplication :one
SELECT
    va.id, va.veteran_id, va.job_listing_id, va.status, va.match_score,
    va.notes, va.created_at, va.updated_at
FROM veteran_applications va
WHERE va.id = $1 AND va.veteran_id = $2
`

type GetVeteranApplicationParams struct {
	ID        int32 `json:"id"`
	VeteranID int32 `json:"veteran_id"`
}

type GetVeteranApplicationRow struct {
	ID           int32              `json:"id"`
	VeteranID    int32              `json:"veteran_id"`
	JobListingID int32              `json:"job_listing_id"`
	Status       string             `json:"status"`
	MatchScore   int32              `json:"match_score"`
	Notes        string             `json:"notes"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	UpdatedAt    pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) GetVeteranApplication(ctx context.Context, arg GetVeteranApplicationParams) (GetVeteranApplicationRow, error) {
	row := q.db.QueryRow(ctx, getVeteranApplication, arg.ID, arg.VeteranID)
	var i GetVeteranApplicationRow
	err := row.Scan(
		&i.ID,
		&i.VeteranID,
		&i.JobListingID,
		&i.Status,
		&i.MatchScore,
		&i.Notes,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getVeteranApplications = `-- name: GetVeteranApplications :many
SELECT
    va.id, va.status, va.match_score, va.match_details, va.notes, va.created_at, va.updated_at,
    jl.id AS job_listing_id, jl.title, jl.description, jl.location,
    jl.salary_min, jl.salary_max, jl.employment_type, jl.wotc_eligible,
    cr.sector, cr.title AS role_title,
    e.company_name
FROM veteran_applications va
JOIN job_listings jl ON jl.id = va.job_listing_id
JOIN civilian_roles cr ON cr.id = jl.civilian_role_id
LEFT JOIN employers e ON e.id = jl.employer_id
WHERE va.veteran_id = $1
ORDER BY
    CASE va.status
        WHEN 'placed' THEN 1
        WHEN 'interviewing' THEN 2
        WHEN 'introduced' THEN 3
        WHEN 'interested' THEN 4
        WHEN 'matched' THEN 5
    END,
    va.match_score DESC
`

type GetVeteranApplicationsRow struct {
	ID             int32              `json:"id"`
	Status         string             `json:"status"`
	MatchScore     int32              `json:"match_score"`
	MatchDetails   []byte             `json:"match_details"`
	Notes          string             `json:"notes"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
	UpdatedAt      pgtype.Timestamptz `json:"updated_at"`
	JobListingID   int32              `json:"job_listing_id"`
	Title          string             `json:"title"`
	Description    string             `json:"description"`
	Location       string             `json:"location"`
	SalaryMin      int32              `json:"salary_min"`
	SalaryMax      int32              `json:"salary_max"`
	EmploymentType string             `json:"employment_type"`
	WotcEligible   bool               `json:"wotc_eligible"`
	Sector         string             `json:"sector"`
	RoleTitle      string             `json:"role_title"`
	CompanyName    pgtype.Text        `json:"company_name"`
}

// Returns all applications for a veteran with job listing and employer details
func (q *Queries) GetVeteranApplications(ctx context.Context, veteranID int32) ([]GetVeteranApplicationsRow, error) {
	rows, err := q.db.Query(ctx, getVeteranApplications, veteranID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetVeteranApplicationsRow
	for rows.Next() {
		var i GetVeteranApplicationsRow
		if err := rows.Scan(
			&i.ID,
			&i.Status,
			&i.MatchScore,
			&i.MatchDetails,
			&i.Notes,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.JobListingID,
			&i.Title,
			&i.Description,
			&i.Location,
			&i.SalaryMin,
			&i.SalaryMax,
			&i.EmploymentType,
			&i.WotcEligible,
			&i.Sector,
			&i.RoleTitle,
			&i.CompanyName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateApplicationMatchDetails = `-- name: UpdateApplicationMatchDetails :exec
UPDATE veteran_applications SET
    match_score = $2,
    match_details = $3,
    updated_at = NOW()
WHERE id = $1
`

type UpdateApplicationMatchDetailsParams struct {
	ID           int32  `json:"id"`
	MatchScore   int32  `json:"match_score"`
	MatchDetails []byte `json:"match_details"`
}

// Store hybrid match score and breakdown details
func (q *Queries) UpdateApplicationMatchDetails(ctx context.Context, arg UpdateApplicationMatchDetailsParams) error {
	_, err := q.db.Exec(ctx, updateApplicationMatchDetails, arg.ID, arg.MatchScore, arg.MatchDetails)
	return err
}

const updateApplicationStatus = `-- name: UpdateApplicationStatus :one
UPDATE veteran_applications SET
    status = $3,
    updated_at = NOW()
WHERE id = $1 AND veteran_id = $2
RETURNING id, veteran_id, job_listing_id, status, match_score, notes, created_at, updated_at
`

type UpdateApplicationStatusParams struct {
	ID        int32  `json:"id"`
	VeteranID int32  `json:"veteran_id"`
	Status    string `json:"status"`
}

type UpdateApplicationStatusRow struct {
	ID           int32              `json:"id"`
	VeteranID    int32              `json:"veteran_id"`
	JobListingID int32              `json:"job_listing_id"`
	Status       string             `json:"status"`
	MatchScore   int32              `json:"match_score"`
	Notes        string             `json:"notes"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	UpdatedAt    pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) UpdateApplicationStatus(ctx context.Context, arg UpdateApplicationStatusParams) (UpdateApplicationStatusRow, error) {
	row := q.db.QueryRow(ctx, updateApplicationStatus, arg.ID, arg.VeteranID, arg.Status)
	var i UpdateApplicationStatusRow
	err := row.Scan(
		&i.ID,
		&i.VeteranID,
		&i.JobListingID,
		&i.Status,
		&i.MatchScore,
		&i.Notes,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
