// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: employers.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countCandidatesForEmployer = `-- name: CountCandidatesForEmployer :one
SELECT COUNT(DISTINCT va.veteran_id) AS total_candidates
FROM veteran_applications va
JOIN job_listings jl ON jl.id = va.job_listing_id
WHERE jl.employer_id = $1 AND va.status != 'matched'
`

func (q *Queries) CountCandidatesForEmployer(ctx context.Context, employerID pgtype.Int4) (int64, error) {
	row := q.db.QueryRow(ctx, countCandidatesForEmployer, employerID)
	var total_candidates int64
	err := row.Scan(&total_candidates)
	return total_candidates, err
}

const createEmployer = `-- name: CreateEmployer :one
INSERT INTO employers (email, company_name, contact_name, sector, location, description, password_hash)
VALUES ($1, $2, $3, $4, $5, $6, $7)
ON CONFLICT (email) DO NOTHING
RETURNING id, email, company_name, contact_name, sector, location, description, password_hash, is_active, created_at, updated_at
`

type CreateEmployerParams struct {
	Email        string `json:"email"`
	CompanyName  string `json:"company_name"`
	ContactName  string `json:"contact_name"`
	Sector       string `json:"sector"`
	Location     string `json:"location"`
	Description  string `json:"description"`
	PasswordHash string `json:"password_hash"`
}

type CreateEmployerRow struct {
	ID           int32              `json:"id"`
	Email        string             `json:"email"`
	CompanyName  string             `json:"company_name"`
	ContactName  string             `json:"contact_name"`
	Sector       string             `json:"sector"`
	Location     string             `json:"location"`
	Description  string             `json:"description"`
	PasswordHash string             `json:"password_hash"`
	IsActive     bool               `json:"is_active"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	UpdatedAt    pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) CreateEmployer(ctx context.Context, arg CreateEmployerParams) (CreateEmployerRow, error) {
	row := q.db.QueryRow(ctx, createEmployer,
		arg.Email,
		arg.CompanyName,
		arg.ContactName,
		arg.Sector,
		arg.Location,
		arg.Description,
		arg.PasswordHash,
	)
	var i CreateEmployerRow
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.CompanyName,
		&i.ContactName,
		&i.Sector,
		&i.Location,
		&i.Description,
		&i.PasswordHash,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createJobListing = `-- name: CreateJobListing :one
INSERT INTO job_listings (employer_id, civilian_role_id, title, description, requirements, location, salary_min, salary_max, employment_type, wotc_eligible, tasks, benefits, mos_codes_preferred)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13)
RETURNING id, employer_id, civilian_role_id, title, description, requirements, location, salary_min, salary_max, employment_type, wotc_eligible, is_active, posted_at, expires_at, tasks, benefits, mos_codes_preferred
`

type CreateJobListingParams struct {
	EmployerID        pgtype.Int4 `json:"employer_id"`
	CivilianRoleID    int32       `json:"civilian_role_id"`
	Title             string      `json:"title"`
	Description       string      `json:"description"`
	Requirements      []string    `json:"requirements"`
	Location          string      `json:"location"`
	SalaryMin         int32       `json:"salary_min"`
	SalaryMax         int32       `json:"salary_max"`
	EmploymentType    string      `json:"employment_type"`
	WotcEligible      bool        `json:"wotc_eligible"`
	Tasks             []string    `json:"tasks"`
	Benefits          []string    `json:"benefits"`
	MosCodesPreferred []string    `json:"mos_codes_preferred"`
}

type CreateJobListingRow struct {
	ID                int32              `json:"id"`
	EmployerID        pgtype.Int4        `json:"employer_id"`
	CivilianRoleID    int32              `json:"civilian_role_id"`
	Title             string             `json:"title"`
	Description       string             `json:"description"`
	Requirements      []string           `json:"requirements"`
	Location          string             `json:"location"`
	SalaryMin         int32              `json:"salary_min"`
	SalaryMax         int32              `json:"salary_max"`
	EmploymentType    string             `json:"employment_type"`
	WotcEligible      bool               `json:"wotc_eligible"`
	IsActive          bool               `json:"is_active"`
	PostedAt          pgtype.Timestamptz `json:"posted_at"`
	ExpiresAt         pgtype.Timestamptz `json:"expires_at"`
	Tasks             []string           `json:"tasks"`
	Benefits          []string           `json:"benefits"`
	MosCodesPreferred []string           `json:"mos_codes_preferred"`
}

func (q *Queries) CreateJobListing(ctx context.Context, arg CreateJobListingParams) (CreateJobListingRow, error) {
	row := q.db.QueryRow(ctx, createJobListing,
		arg.EmployerID,
		arg.CivilianRoleID,
		arg.Title,
		arg.Description,
		arg.Requirements,
		arg.Location,
		arg.SalaryMin,
		arg.SalaryMax,
		arg.EmploymentType,
		arg.WotcEligible,
		arg.Tasks,
		arg.Benefits,
		arg.MosCodesPreferred,
	)
	var i CreateJobListingRow
	err := row.Scan(
		&i.ID,
		&i.EmployerID,
		&i.CivilianRoleID,
		&i.Title,
		&i.Description,
		&i.Requirements,
		&i.Location,
		&i.SalaryMin,
		&i.SalaryMax,
		&i.EmploymentType,
		&i.WotcEligible,
		&i.IsActive,
		&i.PostedAt,
		&i.ExpiresAt,
		&i.Tasks,
		&i.Benefits,
		&i.MosCodesPreferred,
	)
	return i, err
}

const deleteJobListing = `-- name: DeleteJobListing :exec
DELETE FROM job_listings WHERE id = $1 AND employer_id = $2
`

type DeleteJobListingParams struct {
	ID         int32       `json:"id"`
	EmployerID pgtype.Int4 `json:"employer_id"`
}

func (q *Queries) DeleteJobListing(ctx context.Context, arg DeleteJobListingParams) error {
	_, err := q.db.Exec(ctx, deleteJobListing, arg.ID, arg.EmployerID)
	return err
}

const getEmployerByEmail = `-- name: GetEmployerByEmail :one
SELECT id, email, company_name, contact_name, sector, location, description, password_hash, is_active, created_at, updated_at
FROM employers
WHERE email = $1
`

type GetEmployerByEmailRow struct {
	ID           int32              `json:"id"`
	Email        string             `json:"email"`
	CompanyName  string             `json:"company_name"`
	ContactName  string             `json:"contact_name"`
	Sector       string             `json:"sector"`
	Location     string             `json:"location"`
	Description  string             `json:"description"`
	PasswordHash string             `json:"password_hash"`
	IsActive     bool               `json:"is_active"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	UpdatedAt    pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) GetEmployerByEmail(ctx context.Context, email string) (GetEmployerByEmailRow, error) {
	row := q.db.QueryRow(ctx, getEmployerByEmail, email)
	var i GetEmployerByEmailRow
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.CompanyName,
		&i.ContactName,
		&i.Sector,
		&i.Location,
		&i.Description,
		&i.PasswordHash,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getEmployerByID = `-- name: GetEmployerByID :one
SELECT id, email, company_name, contact_name, sector, location, description, password_hash, is_active, created_at, updated_at
FROM employers
WHERE id = $1
`

type GetEmployerByIDRow struct {
	ID           int32              `json:"id"`
	Email        string             `json:"email"`
	CompanyName  string             `json:"company_name"`
	ContactName  string             `json:"contact_name"`
	Sector       string             `json:"sector"`
	Location     string             `json:"location"`
	Description  string             `json:"description"`
	PasswordHash string             `json:"password_hash"`
	IsActive     bool               `json:"is_active"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	UpdatedAt    pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) GetEmployerByID(ctx context.Context, id int32) (GetEmployerByIDRow, error) {
	row := q.db.QueryRow(ctx, getEmployerByID, id)
	var i GetEmployerByIDRow
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.CompanyName,
		&i.ContactName,
		&i.Sector,
		&i.Location,
		&i.Description,
		&i.PasswordHash,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getEmployerDashboardStats = `-- name: GetEmployerDashboardStats :one
SELECT
    COUNT(*) FILTER (WHERE is_active = true) AS active_listings,
    COUNT(*) FILTER (WHERE is_active = false) AS inactive_listings,
    COUNT(*) AS total_listings
FROM job_listings
WHERE employer_id = $1
`

type GetEmployerDashboardStatsRow struct {
	ActiveListings   int64 `json:"active_listings"`
	InactiveListings int64 `json:"inactive_listings"`
	TotalListings    int64 `json:"total_listings"`
}

func (q *Queries) GetEmployerDashboardStats(ctx context.Context, employerID pgtype.Int4) (GetEmployerDashboardStatsRow, error) {
	row := q.db.QueryRow(ctx, getEmployerDashboardStats, employerID)
	var i GetEmployerDashboardStatsRow
	err := row.Scan(&i.ActiveListings, &i.InactiveListings, &i.TotalListings)
	return i, err
}

const getEmployerJobListing = `-- name: GetEmployerJobListing :one
SELECT
    jl.id, jl.title, jl.description, jl.requirements, jl.location,
    jl.salary_min, jl.salary_max, jl.employment_type, jl.wotc_eligible,
    jl.is_active, jl.posted_at, jl.expires_at, jl.tasks, jl.benefits,
    jl.mos_codes_preferred, jl.civilian_role_id,
    cr.onet_code, cr.title AS role_title, cr.sector
FROM job_listings jl
JOIN civilian_roles cr ON cr.id = jl.civilian_role_id
WHERE jl.id = $1 AND jl.employer_id = $2
`

type GetEmployerJobListingParams struct {
	ID         int32       `json:"id"`
	EmployerID pgtype.Int4 `json:"employer_id"`
}

type GetEmployerJobListingRow struct {
	ID                int32              `json:"id"`
	Title             string             `json:"title"`
	Description       string             `json:"description"`
	Requirements      []string           `json:"requirements"`
	Location          string             `json:"location"`
	SalaryMin         int32              `json:"salary_min"`
	SalaryMax         int32              `json:"salary_max"`
	EmploymentType    string             `json:"employment_type"`
	WotcEligible      bool               `json:"wotc_eligible"`
	IsActive          bool               `json:"is_active"`
	PostedAt          pgtype.Timestamptz `json:"posted_at"`
	ExpiresAt         pgtype.Timestamptz `json:"expires_at"`
	Tasks             []string           `json:"tasks"`
	Benefits          []string           `json:"benefits"`
	MosCodesPreferred []string           `json:"mos_codes_preferred"`
	CivilianRoleID    int32              `json:"civilian_role_id"`
	OnetCode          string             `json:"onet_code"`
	RoleTitle         string             `json:"role_title"`
	Sector            string             `json:"sector"`
}

func (q *Queries) GetEmployerJobListing(ctx context.Context, arg GetEmployerJobListingParams) (GetEmployerJobListingRow, error) {
	row := q.db.QueryRow(ctx, getEmployerJobListing, arg.ID, arg.EmployerID)
	var i GetEmployerJobListingRow
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Description,
		&i.Requirements,
		&i.Location,
		&i.SalaryMin,
		&i.SalaryMax,
		&i.EmploymentType,
		&i.WotcEligible,
		&i.IsActive,
		&i.PostedAt,
		&i.ExpiresAt,
		&i.Tasks,
		&i.Benefits,
		&i.MosCodesPreferred,
		&i.CivilianRoleID,
		&i.OnetCode,
		&i.RoleTitle,
		&i.Sector,
	)
	return i, err
}

const listCandidatesForEmployer = `-- name: ListCandidatesForEmployer :many
SELECT
    va.id AS application_id, va.status, va.match_score, va.created_at AS applied_at,
    v.id AS veteran_id, v.name, v.mos_code, v.rank, v.years_of_service,
    v.separation_date, v.location AS veteran_location, v.journey_step,
    jl.id AS job_listing_id, jl.title AS job_title,
    cr.sector
FROM veteran_applications va
JOIN veterans v ON v.id = va.veteran_id
JOIN job_listings jl ON jl.id = va.job_listing_id
JOIN civilian_roles cr ON cr.id = jl.civilian_role_id
WHERE jl.employer_id = $1 AND va.status != 'matched'
ORDER BY
    CASE va.status
        WHEN 'placed' THEN 1
        WHEN 'interviewing' THEN 2
        WHEN 'introduced' THEN 3
        WHEN 'interested' THEN 4
    END,
    va.match_score DESC
`

type ListCandidatesForEmployerRow struct {
	ApplicationID   int32              `json:"application_id"`
	Status          string             `json:"status"`
	MatchScore      int32              `json:"match_score"`
	AppliedAt       pgtype.Timestamptz `json:"applied_at"`
	VeteranID       int32              `json:"veteran_id"`
	Name            string             `json:"name"`
	MosCode         pgtype.Text        `json:"mos_code"`
	Rank            string             `json:"rank"`
	YearsOfService  int32              `json:"years_of_service"`
	SeparationDate  pgtype.Date        `json:"separation_date"`
	VeteranLocation string             `json:"veteran_location"`
	JourneyStep     string             `json:"journey_step"`
	JobListingID    int32              `json:"job_listing_id"`
	JobTitle        string             `json:"job_title"`
	Sector          string             `json:"sector"`
}

func (q *Queries) ListCandidatesForEmployer(ctx context.Context, employerID pgtype.Int4) ([]ListCandidatesForEmployerRow, error) {
	rows, err := q.db.Query(ctx, listCandidatesForEmployer, employerID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListCandidatesForEmployerRow
	for rows.Next() {
		var i ListCandidatesForEmployerRow
		if err := rows.Scan(
			&i.ApplicationID,
			&i.Status,
			&i.MatchScore,
			&i.AppliedAt,
			&i.VeteranID,
			&i.Name,
			&i.MosCode,
			&i.Rank,
			&i.YearsOfService,
			&i.SeparationDate,
			&i.VeteranLocation,
			&i.JourneyStep,
			&i.JobListingID,
			&i.JobTitle,
			&i.Sector,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCivilianRoles = `-- name: ListCivilianRoles :many
SELECT id, onet_code, title, description, sector, avg_salary_min, avg_salary_max
FROM civilian_roles
ORDER BY sector, title
`

func (q *Queries) ListCivilianRoles(ctx context.Context) ([]CivilianRole, error) {
	rows, err := q.db.Query(ctx, listCivilianRoles)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []CivilianRole
	for rows.Next() {
		var i CivilianRole
		if err := rows.Scan(
			&i.ID,
			&i.OnetCode,
			&i.Title,
			&i.Description,
			&i.Sector,
			&i.AvgSalaryMin,
			&i.AvgSalaryMax,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listEmployerJobListings = `-- name: ListEmployerJobListings :many
SELECT
    jl.id, jl.title, jl.description, jl.requirements, jl.location,
    jl.salary_min, jl.salary_max, jl.employment_type, jl.wotc_eligible,
    jl.is_active, jl.posted_at, jl.expires_at, jl.tasks, jl.benefits,
    jl.mos_codes_preferred,
    cr.onet_code, cr.title AS role_title, cr.sector
FROM job_listings jl
JOIN civilian_roles cr ON cr.id = jl.civilian_role_id
WHERE jl.employer_id = $1
ORDER BY jl.posted_at DESC
`

type ListEmployerJobListingsRow struct {
	ID                int32              `json:"id"`
	Title             string             `json:"title"`
	Description       string             `json:"description"`
	Requirements      []string           `json:"requirements"`
	Location          string             `json:"location"`
	SalaryMin         int32              `json:"salary_min"`
	SalaryMax         int32              `json:"salary_max"`
	EmploymentType    string             `json:"employment_type"`
	WotcEligible      bool               `json:"wotc_eligible"`
	IsActive          bool               `json:"is_active"`
	PostedAt          pgtype.Timestamptz `json:"posted_at"`
	ExpiresAt         pgtype.Timestamptz `json:"expires_at"`
	Tasks             []string           `json:"tasks"`
	Benefits          []string           `json:"benefits"`
	MosCodesPreferred []string           `json:"mos_codes_preferred"`
	OnetCode          string             `json:"onet_code"`
	RoleTitle         string             `json:"role_title"`
	Sector            string             `json:"sector"`
}

func (q *Queries) ListEmployerJobListings(ctx context.Context, employerID pgtype.Int4) ([]ListEmployerJobListingsRow, error) {
	rows, err := q.db.Query(ctx, listEmployerJobListings, employerID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListEmployerJobListingsRow
	for rows.Next() {
		var i ListEmployerJobListingsRow
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Description,
			&i.Requirements,
			&i.Location,
			&i.SalaryMin,
			&i.SalaryMax,
			&i.EmploymentType,
			&i.WotcEligible,
			&i.IsActive,
			&i.PostedAt,
			&i.ExpiresAt,
			&i.Tasks,
			&i.Benefits,
			&i.MosCodesPreferred,
			&i.OnetCode,
			&i.RoleTitle,
			&i.Sector,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const toggleJobListingActive = `-- name: ToggleJobListingActive :one
UPDATE job_listings SET is_active = NOT is_active
WHERE id = $1 AND employer_id = $2
RETURNING id, employer_id, civilian_role_id, title, description, requirements, location, salary_min, salary_max, employment_type, wotc_eligible, is_active, posted_at, expires_at, tasks, benefits, mos_codes_preferred
`

type ToggleJobListingActiveParams struct {
	ID         int32       `json:"id"`
	EmployerID pgtype.Int4 `json:"employer_id"`
}

type ToggleJobListingActiveRow struct {
	ID                int32              `json:"id"`
	EmployerID        pgtype.Int4        `json:"employer_id"`
	CivilianRoleID    int32              `json:"civilian_role_id"`
	Title             string             `json:"title"`
	Description       string             `json:"description"`
	Requirements      []string           `json:"requirements"`
	Location          string             `json:"location"`
	SalaryMin         int32              `json:"salary_min"`
	SalaryMax         int32              `json:"salary_max"`
	EmploymentType    string             `json:"employment_type"`
	WotcEligible      bool               `json:"wotc_eligible"`
	IsActive          bool               `json:"is_active"`
	PostedAt          pgtype.Timestamptz `json:"posted_at"`
	ExpiresAt         pgtype.Timestamptz `json:"expires_at"`
	Tasks             []string           `json:"tasks"`
	Benefits          []string           `json:"benefits"`
	MosCodesPreferred []string           `json:"mos_codes_preferred"`
}

func (q *Queries) ToggleJobListingActive(ctx context.Context, arg ToggleJobListingActiveParams) (ToggleJobListingActiveRow, error) {
	row := q.db.QueryRow(ctx, toggleJobListingActive, arg.ID, arg.EmployerID)
	var i ToggleJobListingActiveRow
	err := row.Scan(
		&i.ID,
		&i.EmployerID,
		&i.CivilianRoleID,
		&i.Title,
		&i.Description,
		&i.Requirements,
		&i.Location,
		&i.SalaryMin,
		&i.SalaryMax,
		&i.EmploymentType,
		&i.WotcEligible,
		&i.IsActive,
		&i.PostedAt,
		&i.ExpiresAt,
		&i.Tasks,
		&i.Benefits,
		&i.MosCodesPreferred,
	)
	return i, err
}

const updateCandidateStatus = `-- name: UpdateCandidateStatus :one
UPDATE veteran_applications SET
    status = $3,
    updated_at = NOW()
WHERE veteran_applications.id = $1 AND veteran_applications.job_listing_id IN (SELECT jl.id FROM job_listings jl WHERE jl.employer_id = $2)
RETURNING id, veteran_id, job_listing_id, status, match_score, notes, created_at, updated_at
`

type UpdateCandidateStatusParams struct {
	ID         int32       `json:"id"`
	EmployerID pgtype.Int4 `json:"employer_id"`
	Status     string      `json:"status"`
}

type UpdateCandidateStatusRow struct {
	ID           int32              `json:"id"`
	VeteranID    int32              `json:"veteran_id"`
	JobListingID int32              `json:"job_listing_id"`
	Status       string             `json:"status"`
	MatchScore   int32              `json:"match_score"`
	Notes        string             `json:"notes"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	UpdatedAt    pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) UpdateCandidateStatus(ctx context.Context, arg UpdateCandidateStatusParams) (UpdateCandidateStatusRow, error) {
	row := q.db.QueryRow(ctx, updateCandidateStatus, arg.ID, arg.EmployerID, arg.Status)
	var i UpdateCandidateStatusRow
	err := row.Scan(
		&i.ID,
		&i.VeteranID,
		&i.JobListingID,
		&i.Status,
		&i.MatchScore,
		&i.Notes,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateEmployerProfile = `-- name: UpdateEmployerProfile :one
UPDATE employers SET
    company_name = $2,
    contact_name = $3,
    sector = $4,
    location = $5,
    description = $6,
    updated_at = NOW()
WHERE id = $1
RETURNING id, email, company_name, contact_name, sector, location, description, password_hash, is_active, created_at, updated_at
`

type UpdateEmployerProfileParams struct {
	ID          int32  `json:"id"`
	CompanyName string `json:"company_name"`
	ContactName string `json:"contact_name"`
	Sector      string `json:"sector"`
	Location    string `json:"location"`
	Description string `json:"description"`
}

type UpdateEmployerProfileRow struct {
	ID           int32              `json:"id"`
	Email        string             `json:"email"`
	CompanyName  string             `json:"company_name"`
	ContactName  string             `json:"contact_name"`
	Sector       string             `json:"sector"`
	Location     string             `json:"location"`
	Description  string             `json:"description"`
	PasswordHash string             `json:"password_hash"`
	IsActive     bool               `json:"is_active"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	UpdatedAt    pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) UpdateEmployerProfile(ctx context.Context, arg UpdateEmployerProfileParams) (UpdateEmployerProfileRow, error) {
	row := q.db.QueryRow(ctx, updateEmployerProfile,
		arg.ID,
		arg.CompanyName,
		arg.ContactName,
		arg.Sector,
		arg.Location,
		arg.Description,
	)
	var i UpdateEmployerProfileRow
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.CompanyName,
		&i.ContactName,
		&i.Sector,
		&i.Location,
		&i.Description,
		&i.PasswordHash,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateJobListing = `-- name: UpdateJobListing :one
UPDATE job_listings SET
    title = $3,
    description = $4,
    requirements = $5,
    location = $6,
    salary_min = $7,
    salary_max = $8,
    employment_type = $9,
    wotc_eligible = $10,
    tasks = $11,
    benefits = $12,
    mos_codes_preferred = $13,
    is_active = $14
WHERE id = $1 AND employer_id = $2
RETURNING id, employer_id, civilian_role_id, title, description, requirements, location, salary_min, salary_max, employment_type, wotc_eligible, is_active, posted_at, expires_at, tasks, benefits, mos_codes_preferred
`

type UpdateJobListingParams struct {
	ID                int32       `json:"id"`
	EmployerID        pgtype.Int4 `json:"employer_id"`
	Title             string      `json:"title"`
	Description       string      `json:"description"`
	Requirements      []string    `json:"requirements"`
	Location          string      `json:"location"`
	SalaryMin         int32       `json:"salary_min"`
	SalaryMax         int32       `json:"salary_max"`
	EmploymentType    string      `json:"employment_type"`
	WotcEligible      bool        `json:"wotc_eligible"`
	Tasks             []string    `json:"tasks"`
	Benefits          []string    `json:"benefits"`
	MosCodesPreferred []string    `json:"mos_codes_preferred"`
	IsActive          bool        `json:"is_active"`
}

type UpdateJobListingRow struct {
	ID                int32              `json:"id"`
	EmployerID        pgtype.Int4        `json:"employer_id"`
	CivilianRoleID    int32              `json:"civilian_role_id"`
	Title             string             `json:"title"`
	Description       string             `json:"description"`
	Requirements      []string           `json:"requirements"`
	Location          string             `json:"location"`
	SalaryMin         int32              `json:"salary_min"`
	SalaryMax         int32              `json:"salary_max"`
	EmploymentType    string             `json:"employment_type"`
	WotcEligible      bool               `json:"wotc_eligible"`
	IsActive          bool               `json:"is_active"`
	PostedAt          pgtype.Timestamptz `json:"posted_at"`
	ExpiresAt         pgtype.Timestamptz `json:"expires_at"`
	Tasks             []string           `json:"tasks"`
	Benefits          []string           `json:"benefits"`
	MosCodesPreferred []string           `json:"mos_codes_preferred"`
}

func (q *Queries) UpdateJobListing(ctx context.Context, arg UpdateJobListingParams) (UpdateJobListingRow, error) {
	row := q.db.QueryRow(ctx, updateJobListing,
		arg.ID,
		arg.EmployerID,
		arg.Title,
		arg.Description,
		arg.Requirements,
		arg.Location,
		arg.SalaryMin,
		arg.SalaryMax,
		arg.EmploymentType,
		arg.WotcEligible,
		arg.Tasks,
		arg.Benefits,
		arg.MosCodesPreferred,
		arg.IsActive,
	)
	var i UpdateJobListingRow
	err := row.Scan(
		&i.ID,
		&i.EmployerID,
		&i.CivilianRoleID,
		&i.Title,
		&i.Description,
		&i.Requirements,
		&i.Location,
		&i.SalaryMin,
		&i.SalaryMax,
		&i.EmploymentType,
		&i.WotcEligible,
		&i.IsActive,
		&i.PostedAt,
		&i.ExpiresAt,
		&i.Tasks,
		&i.Benefits,
		&i.MosCodesPreferred,
	)
	return i, err
}
