// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.0
// source: job_listings.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countActiveJobListings = `-- name: CountActiveJobListings :one
SELECT COUNT(*) FROM job_listings WHERE is_active = true
`

func (q *Queries) CountActiveJobListings(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countActiveJobListings)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const getJobListing = `-- name: GetJobListing :one
SELECT
    jl.id, jl.title, jl.description, jl.requirements, jl.location,
    jl.salary_min, jl.salary_max, jl.employment_type, jl.wotc_eligible,
    jl.is_active, jl.posted_at,
    cr.onet_code, cr.title AS role_title, cr.sector,
    e.id AS employer_id, e.company_name, e.location AS company_location
FROM job_listings jl
JOIN civilian_roles cr ON cr.id = jl.civilian_role_id
LEFT JOIN employers e ON e.id = jl.employer_id
WHERE jl.id = $1
`

type GetJobListingRow struct {
	ID              int32              `json:"id"`
	Title           string             `json:"title"`
	Description     string             `json:"description"`
	Requirements    []string           `json:"requirements"`
	Location        string             `json:"location"`
	SalaryMin       int32              `json:"salary_min"`
	SalaryMax       int32              `json:"salary_max"`
	EmploymentType  string             `json:"employment_type"`
	WotcEligible    bool               `json:"wotc_eligible"`
	IsActive        bool               `json:"is_active"`
	PostedAt        pgtype.Timestamptz `json:"posted_at"`
	OnetCode        string             `json:"onet_code"`
	RoleTitle       string             `json:"role_title"`
	Sector          string             `json:"sector"`
	EmployerID      pgtype.Int4        `json:"employer_id"`
	CompanyName     pgtype.Text        `json:"company_name"`
	CompanyLocation pgtype.Text        `json:"company_location"`
}

func (q *Queries) GetJobListing(ctx context.Context, id int32) (GetJobListingRow, error) {
	row := q.db.QueryRow(ctx, getJobListing, id)
	var i GetJobListingRow
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Description,
		&i.Requirements,
		&i.Location,
		&i.SalaryMin,
		&i.SalaryMax,
		&i.EmploymentType,
		&i.WotcEligible,
		&i.IsActive,
		&i.PostedAt,
		&i.OnetCode,
		&i.RoleTitle,
		&i.Sector,
		&i.EmployerID,
		&i.CompanyName,
		&i.CompanyLocation,
	)
	return i, err
}

const listMatchedJobListings = `-- name: ListMatchedJobListings :many
SELECT
    jl.id, jl.title, jl.description, jl.requirements, jl.location,
    jl.salary_min, jl.salary_max, jl.employment_type, jl.wotc_eligible,
    jl.posted_at, jl.tasks, jl.mos_codes_preferred,
    cr.onet_code, cr.title AS role_title, cr.sector,
    e.id AS employer_id, e.company_name, e.location AS company_location,
    mcm.match_score, mcm.transferable_skills
FROM job_listings jl
JOIN civilian_roles cr ON cr.id = jl.civilian_role_id
JOIN mos_civilian_mappings mcm ON mcm.civilian_role_id = jl.civilian_role_id AND mcm.mos_code = $1
LEFT JOIN employers e ON e.id = jl.employer_id
WHERE jl.is_active = true
ORDER BY mcm.match_score DESC, jl.posted_at DESC
`

type ListMatchedJobListingsRow struct {
	ID                 int32              `json:"id"`
	Title              string             `json:"title"`
	Description        string             `json:"description"`
	Requirements       []string           `json:"requirements"`
	Location           string             `json:"location"`
	SalaryMin          int32              `json:"salary_min"`
	SalaryMax          int32              `json:"salary_max"`
	EmploymentType     string             `json:"employment_type"`
	WotcEligible       bool               `json:"wotc_eligible"`
	PostedAt           pgtype.Timestamptz `json:"posted_at"`
	Tasks              []string           `json:"tasks"`
	MosCodesPreferred  []string           `json:"mos_codes_preferred"`
	OnetCode           string             `json:"onet_code"`
	RoleTitle          string             `json:"role_title"`
	Sector             string             `json:"sector"`
	EmployerID         pgtype.Int4        `json:"employer_id"`
	CompanyName        pgtype.Text        `json:"company_name"`
	CompanyLocation    pgtype.Text        `json:"company_location"`
	MatchScore         int32              `json:"match_score"`
	TransferableSkills []string           `json:"transferable_skills"`
}

// Returns active job listings that match a veteran's MOS code, with match scores
// Includes tasks and mos_codes_preferred for hybrid matching engine.
// Exposes the employer id so the frontend can link from an opportunity card
// to the public company profile at /companies/:id.
func (q *Queries) ListMatchedJobListings(ctx context.Context, mosCode string) ([]ListMatchedJobListingsRow, error) {
	rows, err := q.db.Query(ctx, listMatchedJobListings, mosCode)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListMatchedJobListingsRow
	for rows.Next() {
		var i ListMatchedJobListingsRow
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Description,
			&i.Requirements,
			&i.Location,
			&i.SalaryMin,
			&i.SalaryMax,
			&i.EmploymentType,
			&i.WotcEligible,
			&i.PostedAt,
			&i.Tasks,
			&i.MosCodesPreferred,
			&i.OnetCode,
			&i.RoleTitle,
			&i.Sector,
			&i.EmployerID,
			&i.CompanyName,
			&i.CompanyLocation,
			&i.MatchScore,
			&i.TransferableSkills,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
