// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: magic_tokens.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createMagicToken = `-- name: CreateMagicToken :one
INSERT INTO magic_tokens (email, token, user_type, expires_at)
VALUES ($1, $2, $3, $4)
RETURNING id, email, token, user_type, created_at, expires_at, used
`

type CreateMagicTokenParams struct {
	Email     string             `json:"email"`
	Token     string             `json:"token"`
	UserType  string             `json:"user_type"`
	ExpiresAt pgtype.Timestamptz `json:"expires_at"`
}

func (q *Queries) CreateMagicToken(ctx context.Context, arg CreateMagicTokenParams) (MagicToken, error) {
	row := q.db.QueryRow(ctx, createMagicToken,
		arg.Email,
		arg.Token,
		arg.UserType,
		arg.ExpiresAt,
	)
	var i MagicToken
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Token,
		&i.UserType,
		&i.CreatedAt,
		&i.ExpiresAt,
		&i.Used,
	)
	return i, err
}

const deleteExpiredTokens = `-- name: DeleteExpiredTokens :exec
DELETE FROM magic_tokens WHERE expires_at < NOW() OR used = TRUE
`

func (q *Queries) DeleteExpiredTokens(ctx context.Context) error {
	_, err := q.db.Exec(ctx, deleteExpiredTokens)
	return err
}

const getMagicToken = `-- name: GetMagicToken :one
SELECT id, email, token, user_type, created_at, expires_at, used
FROM magic_tokens
WHERE token = $1 AND expires_at > NOW() AND used = FALSE
`

func (q *Queries) GetMagicToken(ctx context.Context, token string) (MagicToken, error) {
	row := q.db.QueryRow(ctx, getMagicToken, token)
	var i MagicToken
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Token,
		&i.UserType,
		&i.CreatedAt,
		&i.ExpiresAt,
		&i.Used,
	)
	return i, err
}

const markTokenUsed = `-- name: MarkTokenUsed :exec
UPDATE magic_tokens SET used = TRUE WHERE id = $1
`

func (q *Queries) MarkTokenUsed(ctx context.Context, id int32) error {
	_, err := q.db.Exec(ctx, markTokenUsed, id)
	return err
}
