// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqlc

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type CivilianRole struct {
	ID           int32  `json:"id"`
	OnetCode     string `json:"onet_code"`
	Title        string `json:"title"`
	Description  string `json:"description"`
	Sector       string `json:"sector"`
	AvgSalaryMin int32  `json:"avg_salary_min"`
	AvgSalaryMax int32  `json:"avg_salary_max"`
}

type Employer struct {
	ID          int32              `json:"id"`
	Email       string             `json:"email"`
	CompanyName string             `json:"company_name"`
	ContactName string             `json:"contact_name"`
	Sector      string             `json:"sector"`
	Location    string             `json:"location"`
	Description string             `json:"description"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
}

type JobListing struct {
	ID             int32              `json:"id"`
	EmployerID     pgtype.Int4        `json:"employer_id"`
	CivilianRoleID int32              `json:"civilian_role_id"`
	Title          string             `json:"title"`
	Description    string             `json:"description"`
	Requirements   []string           `json:"requirements"`
	Location       string             `json:"location"`
	SalaryMin      int32              `json:"salary_min"`
	SalaryMax      int32              `json:"salary_max"`
	EmploymentType string             `json:"employment_type"`
	IsActive       bool               `json:"is_active"`
	WotcEligible   bool               `json:"wotc_eligible"`
	PostedAt       pgtype.Timestamptz `json:"posted_at"`
	ExpiresAt      pgtype.Timestamptz `json:"expires_at"`
}

type MagicToken struct {
	ID        int32              `json:"id"`
	Email     string             `json:"email"`
	Token     string             `json:"token"`
	UserType  string             `json:"user_type"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	ExpiresAt pgtype.Timestamptz `json:"expires_at"`
	Used      bool               `json:"used"`
}

type MosCivilianMapping struct {
	ID                 int32    `json:"id"`
	MosCode            string   `json:"mos_code"`
	CivilianRoleID     int32    `json:"civilian_role_id"`
	MatchScore         int32    `json:"match_score"`
	TransferableSkills []string `json:"transferable_skills"`
}

type MosCode struct {
	Code        string `json:"code"`
	Title       string `json:"title"`
	Branch      string `json:"branch"`
	Description string `json:"description"`
}

type Session struct {
	ID        string             `json:"id"`
	UserType  string             `json:"user_type"`
	UserID    int32              `json:"user_id"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	ExpiresAt pgtype.Timestamptz `json:"expires_at"`
}

type Veteran struct {
	ID               int32              `json:"id"`
	Email            string             `json:"email"`
	Name             string             `json:"name"`
	MosCode          pgtype.Text        `json:"mos_code"`
	Rank             string             `json:"rank"`
	YearsOfService   int32              `json:"years_of_service"`
	SeparationDate   pgtype.Date        `json:"separation_date"`
	Location         string             `json:"location"`
	PreferredSectors []string           `json:"preferred_sectors"`
	CreatedAt        pgtype.Timestamptz `json:"created_at"`
	UpdatedAt        pgtype.Timestamptz `json:"updated_at"`
	JourneyStep      string             `json:"journey_step"`
}

type VeteranApplication struct {
	ID           int32              `json:"id"`
	VeteranID    int32              `json:"veteran_id"`
	JobListingID int32              `json:"job_listing_id"`
	Status       string             `json:"status"`
	MatchScore   int32              `json:"match_score"`
	Notes        string             `json:"notes"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	UpdatedAt    pgtype.Timestamptz `json:"updated_at"`
}
