// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: mos.sql

package sqlc

import (
	"context"
)

const getMOSCode = `-- name: GetMOSCode :one
SELECT code, title, branch, description
FROM mos_codes
WHERE code = $1
`

func (q *Queries) GetMOSCode(ctx context.Context, code string) (MosCode, error) {
	row := q.db.QueryRow(ctx, getMOSCode, code)
	var i MosCode
	err := row.Scan(
		&i.Code,
		&i.Title,
		&i.Branch,
		&i.Description,
	)
	return i, err
}

const listMOSCodes = `-- name: ListMOSCodes :many
SELECT code, title, branch, description
FROM mos_codes
ORDER BY code
`

func (q *Queries) ListMOSCodes(ctx context.Context) ([]MosCode, error) {
	rows, err := q.db.Query(ctx, listMOSCodes)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []MosCode
	for rows.Next() {
		var i MosCode
		if err := rows.Scan(
			&i.Code,
			&i.Title,
			&i.Branch,
			&i.Description,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const translateMOS = `-- name: TranslateMOS :many
SELECT
    cr.onet_code,
    cr.title,
    cr.description,
    cr.sector,
    cr.avg_salary_min,
    cr.avg_salary_max,
    mcm.match_score,
    mcm.transferable_skills
FROM mos_civilian_mappings mcm
JOIN civilian_roles cr ON cr.id = mcm.civilian_role_id
WHERE mcm.mos_code = $1
ORDER BY mcm.match_score DESC
`

type TranslateMOSRow struct {
	OnetCode           string   `json:"onet_code"`
	Title              string   `json:"title"`
	Description        string   `json:"description"`
	Sector             string   `json:"sector"`
	AvgSalaryMin       int32    `json:"avg_salary_min"`
	AvgSalaryMax       int32    `json:"avg_salary_max"`
	MatchScore         int32    `json:"match_score"`
	TransferableSkills []string `json:"transferable_skills"`
}

func (q *Queries) TranslateMOS(ctx context.Context, mosCode string) ([]TranslateMOSRow, error) {
	rows, err := q.db.Query(ctx, translateMOS, mosCode)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []TranslateMOSRow
	for rows.Next() {
		var i TranslateMOSRow
		if err := rows.Scan(
			&i.OnetCode,
			&i.Title,
			&i.Description,
			&i.Sector,
			&i.AvgSalaryMin,
			&i.AvgSalaryMax,
			&i.MatchScore,
			&i.TransferableSkills,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
