// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: veterans.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createVeteranByEmail = `-- name: CreateVeteranByEmail :one
INSERT INTO veterans (email)
VALUES ($1)
ON CONFLICT (email) DO NOTHING
RETURNING id, email, name, mos_code, rank, years_of_service, separation_date, location, preferred_sectors, journey_step, created_at, updated_at
`

type CreateVeteranByEmailRow struct {
	ID               int32              `json:"id"`
	Email            string             `json:"email"`
	Name             string             `json:"name"`
	MosCode          pgtype.Text        `json:"mos_code"`
	Rank             string             `json:"rank"`
	YearsOfService   int32              `json:"years_of_service"`
	SeparationDate   pgtype.Date        `json:"separation_date"`
	Location         string             `json:"location"`
	PreferredSectors []string           `json:"preferred_sectors"`
	JourneyStep      string             `json:"journey_step"`
	CreatedAt        pgtype.Timestamptz `json:"created_at"`
	UpdatedAt        pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) CreateVeteranByEmail(ctx context.Context, email string) (CreateVeteranByEmailRow, error) {
	row := q.db.QueryRow(ctx, createVeteranByEmail, email)
	var i CreateVeteranByEmailRow
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Name,
		&i.MosCode,
		&i.Rank,
		&i.YearsOfService,
		&i.SeparationDate,
		&i.Location,
		&i.PreferredSectors,
		&i.JourneyStep,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getVeteranByEmail = `-- name: GetVeteranByEmail :one
SELECT id, email, name, mos_code, rank, years_of_service, separation_date, location, preferred_sectors, journey_step, created_at, updated_at
FROM veterans
WHERE email = $1
`

type GetVeteranByEmailRow struct {
	ID               int32              `json:"id"`
	Email            string             `json:"email"`
	Name             string             `json:"name"`
	MosCode          pgtype.Text        `json:"mos_code"`
	Rank             string             `json:"rank"`
	YearsOfService   int32              `json:"years_of_service"`
	SeparationDate   pgtype.Date        `json:"separation_date"`
	Location         string             `json:"location"`
	PreferredSectors []string           `json:"preferred_sectors"`
	JourneyStep      string             `json:"journey_step"`
	CreatedAt        pgtype.Timestamptz `json:"created_at"`
	UpdatedAt        pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) GetVeteranByEmail(ctx context.Context, email string) (GetVeteranByEmailRow, error) {
	row := q.db.QueryRow(ctx, getVeteranByEmail, email)
	var i GetVeteranByEmailRow
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Name,
		&i.MosCode,
		&i.Rank,
		&i.YearsOfService,
		&i.SeparationDate,
		&i.Location,
		&i.PreferredSectors,
		&i.JourneyStep,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getVeteranByID = `-- name: GetVeteranByID :one
SELECT id, email, name, mos_code, rank, years_of_service, separation_date, location, preferred_sectors, journey_step, created_at, updated_at
FROM veterans
WHERE id = $1
`

type GetVeteranByIDRow struct {
	ID               int32              `json:"id"`
	Email            string             `json:"email"`
	Name             string             `json:"name"`
	MosCode          pgtype.Text        `json:"mos_code"`
	Rank             string             `json:"rank"`
	YearsOfService   int32              `json:"years_of_service"`
	SeparationDate   pgtype.Date        `json:"separation_date"`
	Location         string             `json:"location"`
	PreferredSectors []string           `json:"preferred_sectors"`
	JourneyStep      string             `json:"journey_step"`
	CreatedAt        pgtype.Timestamptz `json:"created_at"`
	UpdatedAt        pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) GetVeteranByID(ctx context.Context, id int32) (GetVeteranByIDRow, error) {
	row := q.db.QueryRow(ctx, getVeteranByID, id)
	var i GetVeteranByIDRow
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Name,
		&i.MosCode,
		&i.Rank,
		&i.YearsOfService,
		&i.SeparationDate,
		&i.Location,
		&i.PreferredSectors,
		&i.JourneyStep,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateVeteranJourneyStep = `-- name: UpdateVeteranJourneyStep :one
UPDATE veterans SET
    journey_step = $2,
    updated_at = NOW()
WHERE id = $1
RETURNING id, email, name, mos_code, rank, years_of_service, separation_date, location, preferred_sectors, journey_step, created_at, updated_at
`

type UpdateVeteranJourneyStepParams struct {
	ID          int32  `json:"id"`
	JourneyStep string `json:"journey_step"`
}

type UpdateVeteranJourneyStepRow struct {
	ID               int32              `json:"id"`
	Email            string             `json:"email"`
	Name             string             `json:"name"`
	MosCode          pgtype.Text        `json:"mos_code"`
	Rank             string             `json:"rank"`
	YearsOfService   int32              `json:"years_of_service"`
	SeparationDate   pgtype.Date        `json:"separation_date"`
	Location         string             `json:"location"`
	PreferredSectors []string           `json:"preferred_sectors"`
	JourneyStep      string             `json:"journey_step"`
	CreatedAt        pgtype.Timestamptz `json:"created_at"`
	UpdatedAt        pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) UpdateVeteranJourneyStep(ctx context.Context, arg UpdateVeteranJourneyStepParams) (UpdateVeteranJourneyStepRow, error) {
	row := q.db.QueryRow(ctx, updateVeteranJourneyStep, arg.ID, arg.JourneyStep)
	var i UpdateVeteranJourneyStepRow
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Name,
		&i.MosCode,
		&i.Rank,
		&i.YearsOfService,
		&i.SeparationDate,
		&i.Location,
		&i.PreferredSectors,
		&i.JourneyStep,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateVeteranProfile = `-- name: UpdateVeteranProfile :one
UPDATE veterans SET
    name = $2,
    mos_code = $3,
    rank = $4,
    years_of_service = $5,
    separation_date = $6,
    location = $7,
    preferred_sectors = $8,
    updated_at = NOW()
WHERE id = $1
RETURNING id, email, name, mos_code, rank, years_of_service, separation_date, location, preferred_sectors, journey_step, created_at, updated_at
`

type UpdateVeteranProfileParams struct {
	ID               int32       `json:"id"`
	Name             string      `json:"name"`
	MosCode          pgtype.Text `json:"mos_code"`
	Rank             string      `json:"rank"`
	YearsOfService   int32       `json:"years_of_service"`
	SeparationDate   pgtype.Date `json:"separation_date"`
	Location         string      `json:"location"`
	PreferredSectors []string    `json:"preferred_sectors"`
}

type UpdateVeteranProfileRow struct {
	ID               int32              `json:"id"`
	Email            string             `json:"email"`
	Name             string             `json:"name"`
	MosCode          pgtype.Text        `json:"mos_code"`
	Rank             string             `json:"rank"`
	YearsOfService   int32              `json:"years_of_service"`
	SeparationDate   pgtype.Date        `json:"separation_date"`
	Location         string             `json:"location"`
	PreferredSectors []string           `json:"preferred_sectors"`
	JourneyStep      string             `json:"journey_step"`
	CreatedAt        pgtype.Timestamptz `json:"created_at"`
	UpdatedAt        pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) UpdateVeteranProfile(ctx context.Context, arg UpdateVeteranProfileParams) (UpdateVeteranProfileRow, error) {
	row := q.db.QueryRow(ctx, updateVeteranProfile,
		arg.ID,
		arg.Name,
		arg.MosCode,
		arg.Rank,
		arg.YearsOfService,
		arg.SeparationDate,
		arg.Location,
		arg.PreferredSectors,
	)
	var i UpdateVeteranProfileRow
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Name,
		&i.MosCode,
		&i.Rank,
		&i.YearsOfService,
		&i.SeparationDate,
		&i.Location,
		&i.PreferredSectors,
		&i.JourneyStep,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const upsertVeteran = `-- name: UpsertVeteran :one
INSERT INTO veterans (email, name, mos_code, rank, years_of_service, separation_date, location, preferred_sectors)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
ON CONFLICT (email) DO UPDATE SET
    name = EXCLUDED.name,
    mos_code = EXCLUDED.mos_code,
    rank = EXCLUDED.rank,
    years_of_service = EXCLUDED.years_of_service,
    separation_date = EXCLUDED.separation_date,
    location = EXCLUDED.location,
    preferred_sectors = EXCLUDED.preferred_sectors,
    updated_at = NOW()
RETURNING id, email, name, mos_code, rank, years_of_service, separation_date, location, preferred_sectors, journey_step, created_at, updated_at
`

type UpsertVeteranParams struct {
	Email            string      `json:"email"`
	Name             string      `json:"name"`
	MosCode          pgtype.Text `json:"mos_code"`
	Rank             string      `json:"rank"`
	YearsOfService   int32       `json:"years_of_service"`
	SeparationDate   pgtype.Date `json:"separation_date"`
	Location         string      `json:"location"`
	PreferredSectors []string    `json:"preferred_sectors"`
}

type UpsertVeteranRow struct {
	ID               int32              `json:"id"`
	Email            string             `json:"email"`
	Name             string             `json:"name"`
	MosCode          pgtype.Text        `json:"mos_code"`
	Rank             string             `json:"rank"`
	YearsOfService   int32              `json:"years_of_service"`
	SeparationDate   pgtype.Date        `json:"separation_date"`
	Location         string             `json:"location"`
	PreferredSectors []string           `json:"preferred_sectors"`
	JourneyStep      string             `json:"journey_step"`
	CreatedAt        pgtype.Timestamptz `json:"created_at"`
	UpdatedAt        pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) UpsertVeteran(ctx context.Context, arg UpsertVeteranParams) (UpsertVeteranRow, error) {
	row := q.db.QueryRow(ctx, upsertVeteran,
		arg.Email,
		arg.Name,
		arg.MosCode,
		arg.Rank,
		arg.YearsOfService,
		arg.SeparationDate,
		arg.Location,
		arg.PreferredSectors,
	)
	var i UpsertVeteranRow
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Name,
		&i.MosCode,
		&i.Rank,
		&i.YearsOfService,
		&i.SeparationDate,
		&i.Location,
		&i.PreferredSectors,
		&i.JourneyStep,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
